#图片前缀
IMAGE_SERVER: http://39.106.211.119/


spring:
  #rabbitmq
  rabbitmq:
    host: 94.191.79.185
    port: 5672
    username: guest
    password: guest
  #elasticsearch
  elasticsearch:
    jest:
      uris: http://94.191.79.185:9200/
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 94.191.79.185:9300





